### ISSUE TITLE
Finalizar endpoint do Instagram

### ISSUE THREAD

**Issue by mikaelmello** [unb-cic-esw/data-viz#10]
## Resumo

Poder visualizar em gráficos de linhas a evolução dos dados presentes na planilha Grupos políticos sobre cada conta do Instagram dos atores políticos.

## Critério de aceitação

Assim como já existe para Twitter e Facebook, ao acessar a API no endereço `/instagram` deve-se poder listar todas as contas existentes e a partir dali, para cada conta, visualizar em gráficos de linha a evolução de seus dados (coletados da planilha) ao longo do tempo (e.g. crescimento do número de seguidores ou postagens).

**Comment by alegomes** [comment]
O resumo não faz sentido pra mim, dado que não sei o que significa "estar de acordo com o já feito no Twitter e Facebook".

O critério de aceitação me parece vago, cabendo muitas coisas ao final da sprint. 

> "Poder visualizar os dados coletados da planilha de cada usuário" 

Quais dados? Todos os que estiverem planilhados ou apenas alguns?

>"incluindo visualização de gráficos de linhas para ver a evolução de alguns parâmetros ao longo do tempo."

Gráficos de linhas para alguns dados ou para todos? Evolução de quais parâmetros?

[]s

**Comment by mikaelmello** [comment]
> O resumo não faz sentido pra mim, dado que não sei o que significa "estar de acordo com o já feito no Twitter e Facebook".

@alegomes Tem razão, escrevi do nosso ponto de vista esquecendo que deve ser o do cliente, clarifiquei tanto aqui como na story #11

**Comment by mikaelmello** [comment]
Finalizado no PR #14
