### ISSUE TITLE
Finalizar endpoint do Youtube

### ISSUE THREAD

**Issue by mikaelmello** [unb-cic-esw/data-viz#11]
## Resumo

Poder visualizar em gráficos de linhas a evolução dos dados presentes na planilha Grupos políticos sobre cada conta do Youtube dos atores políticos.

## Critério de aceitação

Assim como já existe para Twitter e Facebook, ao acessar a API no endereço `/youtube` deve-se poder listar todas as contas existentes e a partir dali, para cada conta, visualizar em gráficos de linha a evolução de seus dados (coletados da planilha) ao longo do tempo (e.g. crescimento do número de inscritos ou visualizações totais).

**Comment by rodrigofegui** [comment]
_Endpoint_ está funcional.

Atualização de _Status_:
- _Import_ dos dados já está sendo realizado com sucesso;
- Os gráficos já estão sendo gerados para cada aspecto histórico, para o Youtube.

_To Do_:
- Finalizar e "commitar" os testes realizados;
- Ajuste semântico das rotas existentes.

**Comment by alegomes** [comment]
Mesmo comentário da issue #10

**Comment by cftpontes** [comment]
Resumo:
Permitir a visualização dos dados da sessão Youtube da planilha com a API. Permitir a visualização da evolução temporal do nro. de inscritos, nro. de vídeos e nro. de visualizações de um dado perfil.

Critério de aceitação:
Poder visualizar na API os nomes de todos usuários da planilha de dados e os nomes de seus respectivos perfis no Youtube. Poder visualizar na API os últimos dados coletados (nro. de inscritos, nro. de vídeos, nro. de visualizações) de um dado perfil. Poder visualizar na API os gráficos de linhas da evolução do nro. de inscritos, nro. de vídeos, nro. de visualizações de um dado perfil ao longo do tempo.

**Comment by mikaelmello** [comment]
Finalizado no PR #15
