### ISSUE TITLE
Especificar interface de integração dos dados coletados

### ISSUE THREAD

**Issue by mikaelmello** [unb-cic-esw/data-viz#12]
## Resumo

Discutir com os grupos das outras redes sociais como será a integração dos dados coletados por eles com o nosso sistema de visualização e implementar a nossa parte.

## Detalhes

Um bom ponto de partida é o método sugerido pela Dayanne, onde cada grupo lança os dados coletados em algum _cloud provider_ por trás de uma API que nós usaremos para acessar este dados, interpretar e salvar em nosso banco de dados.

Lembrar de padronizar os esquemas dos arquivos gerados por cada grupo. 

Também adaptar a nossa importação de dados da planilha de modo a usar a nova interface implementada.

## Critério de Aceitação

Possuir a interface definida e funcionando pelo menos com a planilha.

**Comment by alegomes** [comment]
> Discutir com os grupos das outras redes sociais como será a integração dos dados coletados por eles com o nosso sistema de visualização e implementar a nossa parte.

Quer dizer que vocês pretendem se submeter à vontade particular de cada um dos demais grupos?

>Lembrar de padronizar os esquemas dos arquivos gerados por cada grupo.

Por quê? Estão pensando em fazer a integração por meio da troca de arquivos? Isso é tãaaao 1990.....

[]s

**Comment by mikaelmello** [comment]
@alegomes 

> Quer dizer que vocês pretendem se submeter à vontade particular de cada um dos demais grupos?

A intenção é que o output de todos os grupos siga os mesmos padrões

> Por quê? Estão pensando em fazer a integração por meio da troca de arquivos? Isso é tãaaao 1990.....

Nós vamos incentivar todos terem o mesmo método de distribuir os dados (o sugerido pela Dayanne ), porém prefiro não me comprometer e possuir uma interface que também consiga interpretar arquivos manualmente inseridos, no caso de algum dos grupos não conseguirem finalizar suas APIs juntamente com os outros.
