### ISSUE TITLE
Integração com Youtube 

### ISSUE THREAD

**Issue by cftpontes** [unb-cic-esw/data-viz#22]
## Resumo
Como cliente, QUERO acessar os dados mais recentes coletados sobre os atores no Youtube por meio da API de visualização de dados PARA poder acompanhar a evolução da popularidade dos atores nessa rede social.

## Detalhes
Fazer com que a API de visualização de dados acesse o endpoint do Youtube (no link https://youtube-data-monitor.herokuapp.com) para coletar os dados mais recentes e adicioná-los ao banco de dados.

## Critérios de aceitação
Exibir, para qualquer ator com conta no Youtube, um gráfico de linhas mostrando a progressão temporal de algum parâmetro (número de vídeos ou do número de visualizações) com o último ponto correspondente à amostra mais recente daquele parâmetro disponível no endpoint do Youtube.

**Comment by rodrigofegui** [comment]
Aprovado pelo grupo.
Pode ser copiada para as demais redes sociais.
