### ISSUE TITLE
Implementar HateOAS

### ISSUE THREAD

**Issue by mikaelmello** [unb-cic-esw/data-viz#9]
## Resumo

Fazer a API ser navegável a partir do caminho inicial `/`, seguindo a limitação HateOAS

## Detalhes

Basicamente colocar um campo a mais nos endpoints que respondem com JSONs. Este campo (`links`), será uma array com links de direção a partir do endpoint atual. Mais detalhes: https://spring.io/understanding/HATEOAS

Exemplos:

* Atualmente o endereço `/`, não responde nada. Podemos mudar isso incluindo os links iniciais possíveis, onde o usuário pode acessar, uma resposta poderia ser parecida com o seguinte trecho [de código](https://gist.github.com/mikaelmello/065575a3d99096bbe19837ae5a73ca4c).
* Na hora de listar as contas do twitter, exibimos apenas `name` e `username`, adicionando o campo `links`, teríamos algo [como este código](https://gist.github.com/mikaelmello/92f25999c7141f175bf57ebbef4434c2).
* No caso de visualizar uma conta do Twitter, a resposta atual não inclui o que é possível tirar a mais daquela conta, então adiciona-se o campo `links` e lista o que mais pode ser acessado. [Exemplo](https://gist.github.com/mikaelmello/6c97aa3b5a1089dcbcbdb40aad972d41)

## Critério de Aceitação

Todos os endpoints criados devem ser acessíveis seguindo os links iniciais no caminho `/`.

**Comment by alegomes** [comment]
De acordo.

**Comment by mikaelmello** [comment]
Progresso

### Página Inicial `/`
- [x] Links para os 4 endpoints possíveis das 4 redes sociais

### Twitter
- [x] Colocar o link para acessar uma conta específica a partir de `/twitter`
- [x] Colocar o link para acessar a página de importação de dados `/twitter/import`
- [x] Dentro de `/twitter/:username`, colocar links para os 4 possíveis gráficos de linha e a página `latest`

### Facebook
- [x] Colocar o link para acessar uma conta específica a partir de `/facebook`
- [x] Colocar o link para acessar a página de importação de dados `/facebook/import`
- [x] Dentro de `/facebook/:id`, colocar links para os 2 possíveis gráficos de linha e a página `latest`

### Instagram
- [x] Colocar o link para acessar uma conta específica a partir de `/instagram`
- [x] Colocar o link para acessar a página de importação de dados `/instagram/import`
- [x] Dentro de `/instagram/:username`, colocar links para os possíveis gráficos de linha e a página `latest`

### Youtube
- [x] Colocar o link para acessar uma conta específica a partir de `/youtube`
- [x] Colocar o link para acessar a página de importação de dados `/youtube/import`
- [x] Dentro de `/youtube/:id`, colocar links para os possíveis gráficos de linha e a página `latest`

**Comment by mikaelmello** [comment]
Finalizado em #19
